apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rawjs9p92-nodejs
  janus-idp.io/tekton: rawjs9p92-nodejs
  backstage.io/kubernetes-id: rawjs9p92-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rawjs9p92-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
