apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rawjs9p92-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rawjs9p92-nodejs 
  name: rawjs9p92-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rawjs9p92-nodejs 
